#!/usr/bin/env python3
"""
Generates src/qr_install.h - the install QR this firmware shows on its
"Get GUIDON on your phone" settings screen.

WHY THIS SCRIPT EXISTS RATHER THAN A HAND-ROLLED ENCODER IN THE FIRMWARE:
guidon-app's own #/share screen tried exactly that once (see
guidon-app/src/index.html, the comment right above G.share's render()) -  a
QR encoder written specifically for that panel produced matrices a reference
decoder (OpenCV) could not read, and was ripped out before shipping. The
project's standing rule since then: never generate a QR live/in-app: always
a verified static image (or, here, a static bitmap) produced by a REAL
library, checked with an INDEPENDENT decoder round-trip, before it ever
ships. This script is that rule, applied to this fork.

Run it whenever the target URL changes (it shouldn't, casually - this is
GUIDON's one canonical install link, the same one the QR distribution memory
for the main app points at). Re-run, re-verify, recopy qr_install.h - never
hand-edit that generated file.

Requires: `qrcode` (a real, standard QR encoder) and `opencv-python` (an
independent reference decoder, used ONLY to verify - never to generate).
    pip install qrcode opencv-python pillow
"""
import sys

try:
    import qrcode
    from qrcode.constants import ERROR_CORRECT_M
except ImportError:
    sys.exit("gen-install-qr: `qrcode` not installed - pip install qrcode pillow")
try:
    import cv2
except ImportError:
    sys.exit("gen-install-qr: `opencv-python` not installed - pip install opencv-python")

URL = "https://cosmicgrub.github.io/The-Guidon/#/share"
OUT_HEADER = "src/qr_install.h"
OUT_PREVIEW = "docs/install_qr_preview.png"


def main():
    qr = qrcode.QRCode(version=None, error_correction=ERROR_CORRECT_M, box_size=1, border=4)
    qr.add_data(URL)
    qr.make(fit=True)
    matrix = qr.get_matrix()
    n = len(matrix)
    print(f"QR version {qr.version} -> {n}x{n} modules (incl. 4-module quiet zone)")

    # Human-checkable preview (not what the firmware embeds - qr_install.h's
    # packed bit matrix is - but useful for a human to look at, and for the
    # round-trip decode check below to run against).
    preview = qr.make_image(fill_color="black", back_color="white").convert("L")
    preview = preview.resize((n * 6, n * 6), resample=0)
    preview.save(OUT_PREVIEW)

    # ---- Independent decoder round-trip - the whole point of this rule ----
    cv_img = cv2.imread(OUT_PREVIEW, cv2.IMREAD_GRAYSCALE)
    detector = cv2.QRCodeDetector()
    decoded, _points, _ = detector.detectAndDecode(cv_img)
    if decoded != URL:
        sys.exit(
            f"gen-install-qr: ROUND-TRIP FAILED. OpenCV decoded {decoded!r}, "
            f"expected {URL!r}. Refusing to write qr_install.h with an "
            f"unverified matrix - this is exactly the failure mode the "
            f"hand-rolled encoder shipped before."
        )
    print("round-trip verified: OpenCV decoded exactly the target URL.")

    # ---- Pack verified matrix: 1 bit/module, MSB-first, row-major ----
    bytes_per_row = (n + 7) // 8
    packed = bytearray()
    for row in matrix:
        for byte_i in range(bytes_per_row):
            b = 0
            for bit_i in range(8):
                idx = byte_i * 8 + bit_i
                v = 1 if (idx < n and row[idx]) else 0
                b = (b << 1) | v
            packed.append(b)

    wrapped = "\n".join(
        "  " + ", ".join(f"0x{b:02X}" for b in packed[i:i + 16]) + ","
        for i in range(0, len(packed), 16)
    )

    header = f"""// Auto-generated by tools/gen-install-qr.py - DO NOT hand-edit.
// Source: a real, standard QR encoder (Python `qrcode`, error-correction M),
// generated OFFLINE and verified via an independent reference decoder
// (OpenCV QRCodeDetector) round-tripping back to the exact target URL
// before this file was written.
//
// This firmware NEVER generates a QR at runtime - see the standing project
// rule (guidon-app/src/index.html's #/share panel documents the same rule,
// after an earlier hand-rolled in-app encoder shipped unscannable codes).
// This bitmap is that rule applied correctly: static, pre-verified, just
// blitted by main.cpp's drawInstallQr().
//
// Target URL: {URL}
// Matrix: {n}x{n} modules (includes the standard 4-module quiet zone border)
// Packed: 1 bit per module, MSB-first, {bytes_per_row} bytes per row, row-major.

#pragma once
#include <stdint.h>

static const uint8_t INSTALL_QR_SIZE = {n};
static const uint8_t INSTALL_QR_BYTES_PER_ROW = {bytes_per_row};
static const char INSTALL_QR_URL[] = "{URL}";

static const uint8_t INSTALL_QR_BITS[{n} * {bytes_per_row}] = {{
{wrapped}
}};

// bit = INSTALL_QR_BITS[row * INSTALL_QR_BYTES_PER_ROW + col/8] & (0x80 >> (col%8))
"""
    with open(OUT_HEADER, "w") as f:
        f.write(header)
    print(f"wrote {OUT_HEADER} ({len(packed)} bytes packed) and {OUT_PREVIEW}")


if __name__ == "__main__":
    main()
